/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CaseStudy {
  'id' : bigint,
  'title' : string,
  'metrics' : Array<CaseStudyMetric>,
  'challenge' : string,
  'clientQuote' : string,
  'isFeatured' : boolean,
  'approach' : string,
  'outcome' : string,
  'material' : string,
  'industry' : string,
}
export interface CaseStudyMetric { 'value' : string, 'name' : string }
export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'company' : string,
  'timestamp' : Timestamp,
  'projectScope' : string,
}
export interface Service {
  'id' : bigint,
  'tools' : Array<string>,
  'standards' : Array<string>,
  'icon' : string,
  'name' : string,
  'description' : string,
  'methodology' : string,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'getCaseStudies' : ActorMethod<[], Array<CaseStudy>>,
  'getCaseStudy' : ActorMethod<[bigint], [] | [CaseStudy]>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getFeaturedCaseStudies' : ActorMethod<[], Array<CaseStudy>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'submitContact' : ActorMethod<
    [string, string, string, string],
    ContactSubmission
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];