/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CaseStudyMetric = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const CaseStudy = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'metrics' : IDL.Vec(CaseStudyMetric),
  'challenge' : IDL.Text,
  'clientQuote' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'approach' : IDL.Text,
  'outcome' : IDL.Text,
  'material' : IDL.Text,
  'industry' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'timestamp' : Timestamp,
  'projectScope' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'tools' : IDL.Vec(IDL.Text),
  'standards' : IDL.Vec(IDL.Text),
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'methodology' : IDL.Text,
});

export const idlService = IDL.Service({
  'getCaseStudies' : IDL.Func([], [IDL.Vec(CaseStudy)], ['query']),
  'getCaseStudy' : IDL.Func([IDL.Nat], [IDL.Opt(CaseStudy)], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getFeaturedCaseStudies' : IDL.Func([], [IDL.Vec(CaseStudy)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ContactSubmission],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CaseStudyMetric = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const CaseStudy = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'metrics' : IDL.Vec(CaseStudyMetric),
    'challenge' : IDL.Text,
    'clientQuote' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'approach' : IDL.Text,
    'outcome' : IDL.Text,
    'material' : IDL.Text,
    'industry' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'timestamp' : Timestamp,
    'projectScope' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'tools' : IDL.Vec(IDL.Text),
    'standards' : IDL.Vec(IDL.Text),
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'methodology' : IDL.Text,
  });
  
  return IDL.Service({
    'getCaseStudies' : IDL.Func([], [IDL.Vec(CaseStudy)], ['query']),
    'getCaseStudy' : IDL.Func([IDL.Nat], [IDL.Opt(CaseStudy)], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getFeaturedCaseStudies' : IDL.Func([], [IDL.Vec(CaseStudy)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ContactSubmission],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };